FROM python:3.10-slim-bullseye

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Dependencies have been saved in vendor. It is generated by:
# poetry export -f requirements.txt --output requirements.txt
# pip3 install -r requirements.txt -t vendor
# ENV PYTHONPATH=vendor

WORKDIR /app

RUN python -m pip install -r requirements.txt

# Switch to the non-privileged user to run the application.

# Copy the source code into the container.
COPY . .

# Expose the port that the application listens on.
EXPOSE 5000

# Run the application.
CMD python app/app.py
